patterns = {
  ('hashtag',): comment,
  ('singleQuote',): string,
  ('doubleQuote',): string,
  ('type', 'beginBlock', 'num'): arrayType,
  ('var', 'beginBlock', 'num'): arrayType,
  ('type', 'beginBlock', 'type'): mapType,
  ('type', 'beginBlock', 'var'): mapType,
  ('var', 'beginBlock', 'type'): mapType,
  ('var', 'beginBlock', 'var'): mapType,
  ('var', 'var'): typeDeclaration,
  ('type', 'var'): typeDeclaration,
  ('var', 'underline', 'var'): var,
  ('underline', 'var'): var,
  ('var', 'underline'): var,
  ('underline',): var,
  ('num', 'dot', 'num'): floatNumber,
  ('num', 'dot'): floatNumber,
  ('num',): expr,
  ('floatNumber',): expr,
  ('var',): expr,
  ('print', 'lparen', 'expr', 'rparen'): printFunc,
}